### ISSUE TITLE
print an error message off su if you're trying to become root and are already root

### ISSUE THREAD

**Issue by Monarchz3ro** [Monarchz3ro/Silver#17]
this is not as easy as it sounds to solve, thanks to my clusterfuck of a codebase
if you add a simple check going "if self.__user == "root": print error" then `sudo su` fails because it pipes you into su with the presupposition that you're already root
you are allowed to modify both `self.__process_su` and `self.__process_sudo` to fix this

**Comment by Yajus114** [comment]
command sudo not found when I run master.py, what am I missing
