### ISSUE TITLE
port user to their /home directory by default + the implications

### ISSUE THREAD

**Issue by Monarchz3ro** [Monarchz3ro/Silver#18]
afterward, change `su` and `sudo` so that they switch you into the changed user's home directory
after that, implement -p into `su` so it retains the current directory

**Comment by Monarchz3ro** [comment]
partially fixed, i think

**Comment by OcelotWalrus** [comment]
> partially fixed, i think

It should be fully fixed by my PR.

**Comment by Monarchz3ro** [comment]
![image](https://github.com/Monarchz3ro/Silver/assets/151715484/efd008ed-4103-41fb-a333-7bfe023c92de)
you've left out something, and i can't figure out what it is you're trying to do

**Comment by OcelotWalrus** [comment]
That's just me who did weird stuff. I don't know what happened lol.
Should be like this:
```python
if self.__groups == "root":
    self.__current_directory = os.path.join(self.__kernel,"root/root").replace("\\", "/")
else:
    self.__current_directory = os.path.join(self.__kernel,"root/home/{self.__user}").replace("\\", "/")
self.current_directory = self.__current_directory
```

It's a function to change the current folder, depending on the user. If the user is a root, the directory changes to the `/root/` one, else, the directory is `/home/<user>/`. This function is ran when booting and when running the su command without the -p argument. I don't exactly remember why but there had to be a self.current_directory and a self.__current_directory variable.

**Comment by OcelotWalrus** [comment]
I just found out why:

the ls.py script needs the self.__current_directory variable but, it cannot access it. So I made a self.current_directory variable just so it can be accessed. Let me make a quick PR to fix that.

**Comment by OcelotWalrus** [comment]
Checkout #24
