### ISSUE TITLE
some bug report

### ISSUE THREAD

**Issue by OcelotWalrus** [Monarchz3ro/Silver#20]
I tested the su command and here are the issues I've encountered:

- when running su Miriel, I entered Miriel's password (`3thiryseven7`) and it failed, but when using the root password, it worked but it still connected me to the Miriel's account. so the bug is that when 'su'ing any account, it's always the root password that works
- ![image](https://github.com/Monarchz3ro/Silver/assets/87318892/1252154b-fe5e-4223-a977-1e2965af0ec8)
- When running su while being root, it crashes:
- ![image](https://github.com/Monarchz3ro/Silver/assets/87318892/a0f15eb7-f2ed-47a1-b42b-709fe98c3fcf)

**Comment by Monarchz3ro** [comment]
noticed this too, working on a fix

**Comment by Monarchz3ro** [comment]
also, `su user` by default always asks for the root pass, not the target user's pass
edit: nvm, that came out wrong, idk what i was thinking

**Comment by Monarchz3ro** [comment]
i'm taking a break, it is boggling my mind with just how many bugs are in the code
i really messed this up hard
here are the following test cases i'd suggest you use if you are working on your own fix
ill work on this myself in a few hours if this isnt fixed
-
sudo -i (asks for root, does nothing)
sudo -i -s (asks for root, opens root shell)
sudo -u Miriel -s whoami (asks for miriel, opens miriel shell, echoes miriel)
sudo whoami (asks for monarch, echoes sysadmin)
sudo -s (asks for monarch, opens root shell)
sudo su - (asks for monarch, opens root shell)
sudo su  - -c whoami (asks for monarch, opens root shell, echoes sysadmin)
sudo su (asks for monarch, changes to root without shell)
sudo su Miriel (asks for monarch, changes to miriel without a shell)
sudo su - Miriel (asks for monarch, opens miriel shell)
su Miriel -c whoami (asks for miriel, changes to miriel without a shell, echoes miriel)
-

**Comment by Monarchz3ro** [comment]
im not sure why the comment above is boldened

**Comment by Yajus114** [comment]
Using a "#" makes them big and bold
# This msg has a '#' in the beginning and therefore is big

**Comment by Monarchz3ro** [comment]
nothing in my message has a hashtag though

**Comment by Monarchz3ro** [comment]
the way i'd go around fixing it is removing the su function entirely and rewriting it from scratch

**Comment by OcelotWalrus** [comment]
> the way i'd go around fixing it is removing the su function entirely and rewriting it from scratch

Better idea. I could work on that if you want.

**Comment by Monarchz3ro** [comment]
If you want to. I'm going to work on it if you or Yajus don't

**Comment by OcelotWalrus** [comment]
If I do it it's going to be this week-end though. Or maybe on Thursday.

**Comment by Monarchz3ro** [comment]
I'll do it then, no worries

**Comment by Monarchz3ro** [comment]
EVERY issue has been mostly fixed, _except_ an incredibly crucial combination
`sudo su`
sudo without the -s arg restores you back to the previous user once it has finished running, and that means it effectively drowns out the changes made by `su`

ideally, `sudo su` should ask for Monarch, switch to root without opening a shell
look up test cases i threw if you're attempting to try and fix this behaviour

**Comment by OcelotWalrus** [comment]
> ideally, sudo su should ask for Monarch, switch to root without opening a shell
look up test cases i threw if you're attempting to try and fix this behaviour

yes.

**Comment by Monarchz3ro** [comment]
![image](https://github.com/Monarchz3ro/Silver/assets/151715484/85fd96b7-7c6d-4f0e-bc94-4e16967ce91d)
EVERY SINGLE BUG WE HAD WITH SUDO AND SU IS FIXED

GO WILD
IT PASSES EVERY SINGLE TEST CASE

**Comment by OcelotWalrus** [comment]
Nice!
