### ISSUE TITLE
another bug

### ISSUE THREAD

**Issue by OcelotWalrus** [Monarchz3ro/Silver#21]
Sorry man, but it seems there's another bug:
![image](https://github.com/Monarchz3ro/Silver/assets/87318892/474b01e0-4a2b-44fb-83fa-ede30df7d670)

**Comment by Monarchz3ro** [comment]
test is a non critical command, don't worry about it (i forgot to put it out of the damn branch)

**Comment by Monarchz3ro** [comment]
![image](https://github.com/Monarchz3ro/Silver/assets/151715484/52cac0f2-a5f5-4e1c-8f68-2505b00ba847)
this i forgot to remove
